/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Animatix Pro Documentation",
  "tagline": "Unity's most powerful visual animation system",
  "favicon": "img/logo/animatix-pro-logo-small.svg",
  "url": "https://oodestudios.github.io",
  "baseUrl": "/animatix-pro-docs/",
  "organizationName": "oodestudios",
  "projectName": "animatix-pro-docs",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "C:\\Users\\AMIR\\animatix-pro-docs\\sidebars.js",
          "editUrl": "https://github.com/oodestudios/animatix-pro-docs/tree/main/",
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true
        },
        "blog": false,
        "theme": {
          "customCss": "C:\\Users\\AMIR\\animatix-pro-docs\\src\\css\\custom.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**"
          ],
          "filename": "sitemap.xml"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/animatix-pro-social-card.jpg",
    "navbar": {
      "title": "Animatix Pro",
      "logo": {
        "alt": "Animatix Pro Logo",
        "src": "img/logo/animatix-pro-logo-small.svg",
        "width": 40,
        "height": 40,
        "href": "#"
      },
      "hideOnScroll": false,
      "items": [
        {
          "type": "doc",
          "docId": "getting-started/introduction",
          "position": "left",
          "label": "Documentation"
        },
        {
          "type": "dropdown",
          "label": "API Reference",
          "position": "left",
          "items": [
            {
              "label": "Core Classes",
              "to": "/docs/api-reference/overview"
            },
            {
              "label": "Examples",
              "to": "/docs/api-reference/examples"
            }
          ]
        },
        {
          "href": "https://github.com/oodestudios/animatix-pro-docs",
          "label": "GitHub",
          "position": "right",
          "className": "navbar__item--github"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "logo": {
        "alt": "Animatix Pro Logo",
        "src": "img/logo/animatix-pro-logo-small.svg",
        "width": 32,
        "height": 32
      },
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Getting Started",
              "to": "/docs/getting-started/introduction"
            },
            {
              "label": "Core Concepts",
              "to": "/docs/core-concepts/graphflow-system"
            },
            {
              "label": "API Reference",
              "to": "/docs/api-reference/overview"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Examples",
              "to": "/docs/examples/ui-ux-animations"
            },
            {
              "label": "Best Practices",
              "to": "/docs/best-practices/organization"
            },
            {
              "label": "Troubleshooting",
              "to": "/docs/troubleshooting/common-issues"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/oodestudios/animatix-pro-docs"
            },
            {
              "label": "Unity Asset Store",
              "href": "https://assetstore.unity.com/packages/tools/animation/animatix-pro"
            },
            {
              "label": "Support",
              "href": "mailto:oode.contact@gmail.com"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 OODE Studios. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "csharp"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "announcementBar": {
      "id": "support_us",
      "content": "🎉 Animatix Pro is now available on Unity Asset Store! <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://assetstore.unity.com/packages/tools/animation/animatix-pro\">Get it now</a>",
      "backgroundColor": "rgba(139, 58, 58, 0.9)",
      "textColor": "#ffffff",
      "isCloseable": true
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
